# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dyusuf <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/23 11:30:13 by dyusuf            #+#    #+#              #
#    Updated: 2020/01/23 22:13:58 by dyusuf           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_cat
SRCS=srcs/*.c

all:
	@gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)

clean:
	@rm -f *.o

fclean: clean
	@rm -f $(NAME)

re: fclean re
