# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dyusuf <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/20 19:40:15 by dyusuf            #+#    #+#              #
#    Updated: 2020/01/20 19:54:52 by dyusuf           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op

.PHONY: clean all

all:
	@gcc -Wall -Werror -Wextra -o $(NAME) do_advanced.c io.c opp.c

clean:
	@rm -f *.o
